server:
  port: 80
  
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      
  thymeleaf:
    cache: false
    prefix: classpath:/templates/ 
    suffix: .html
  datasource:
    url: jdbc:log4jdbc:mariadb://team5.cap6eghyz9of.ap-northeast-2.rds.amazonaws.com:3306/team5
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: team5
    password: alswn37911

    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
      connection-init-sql: select now()

mybatis: 
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    

upload:
  file-path: C:\dev\upload\
  
download:
  file-path: file:///dev/upload/
  resource-url: /file/**
  
jwt:
  secret: rlaghdrbsrlaalswn.3791-khk
  expire: 3600000
  
   
 
  
